-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    addr VARCHAR(255) NOT NULL,
    balance FLOAT
);

CREATE TABLE Category (
    name VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE Product (
    id INT NOT NULL,
    seller_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    details VARCHAR (255),
    price FLOAT NOT NULL,
    image VARCHAR(100000), 
    type VARCHAR (255),
    quantity INT,
    PRIMARY KEY (id, seller_id),
    FOREIGN KEY (seller_id) REFERENCES Users(id),
    FOREIGN KEY (type) REFERENCES Category(name)
);

CREATE TABLE SellerReview ( 
    author_id INT,
    seller_id INT, 
    rating FLOAT NOT NULL,
    date_and_time TIMESTAMP NOT NULL,
    PRIMARY KEY (author_id, seller_id),
    FOREIGN KEY (author_id) REFERENCES Users(id),
    FOREIGN KEY (seller_id) REFERENCES Users(id)
);

CREATE TABLE ProductReview (
    author_id INT,
    product_id INT,
    seller_id INT,
    rating FLOAT NOT NULL,
    date_and_time TIMESTAMP NOT NULL,
    PRIMARY KEY (author_id, product_id),
    FOREIGN KEY (author_id) REFERENCES Users(id),
    FOREIGN KEY (seller_id) REFERENCES Users(id),
    FOREIGN KEY (product_id, seller_id) REFERENCES Product(id, seller_id)
);

CREATE TABLE Cart (
    user_id INT,
    product_id INT,
    seller_id INT,
    quantity INT,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (product_id, seller_id) REFERENCES Product(id, seller_id),
    FOREIGN KEY (seller_id) REFERENCES Users(id)
);

CREATE TABLE Orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    date_and_time TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE OrderContains(
    order_id INT,
    fullfilled INT,
    quantity INT,
    price FLOAT,
    product_id INT,
    seller_id INT,
    /*fullfilled 1 yes 0 no*/
    FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    FOREIGN KEY (product_id, seller_id) REFERENCES Product(id, seller_id)
);

